<div class="container">
    <div class="page-header">
        <h1><?php echo $this->ui_title; ?> &raquo; Detail</h1>
    </div>

    <?php echo $this->render('crud/top_nav.phtml'); ?>

    <table class="zebra-striped">
    <thead>
        <th>Name</th>
        <th>Value</th>
    </thead>
    <tbody>
<?php foreach ($this->record as $col => $val): ?>
        <tr>
            <th scope="row"><?php echo $col; ?></th>
            <td><?php echo $val; ?></td>
        </tr>
<?php endforeach; ?>
    </tbody>
    </table>
</div>
