<div class="container">
    <div class="page-header-off">
        <h1><?php echo $this->ui_title; ?></h1>
    </div>
    <p class="new">
        <a href="<?php echo $this->BetterUrl(array('action' => 'create')); ?>" class="btn small">Add new entry</a> -
        <a href="<?php echo $this->BetterUrl(array('action' => 'list')); ?>?reset=1" class="btn small">Show all</a>
    </p>
    <table class="table zebra-striped">
    <thead>
        <tr>
<?php foreach ($this->cols as $column): ?>
            <th><a href="<?php $ot = ($column == $this->order) ? $this->otNew : 'ASC'; echo $this->url(array_merge($this->urlParams, array('o' => $column, 'ot' => $ot))); ?>"><?php echo $column; ?></a></th>
<?php endforeach; ?>
            <th>actions</th>
        </tr>
    </thead>
    <tbody>
<?php foreach ($this->paginator as $row): ?>
        <tr>
<?php $_primary = array(); ?>
<?php foreach ($row as $col => $val): ?>
    <?php
    if (in_array($col, $this->primary)) {
        $_primary[$col] = $val;
    }
    ?>
    <?php if (in_array($col, $this->cols)): ?>
            <td class="data-<?php echo $col; ?>"><?php echo $val; ?></td>
    <?php endif; ?>
<?php endforeach; ?>
            <td>
                <a href="<?php echo $this->BetterUrl(array('action' => 'read', 'primary-key' => serialize($_primary))); ?>">Detail</a>
            </td>
        </tr>
<?php endforeach; ?>
    </tbody>
    </table>
<?php
     echo $this->paginationControl(
            $this->paginator, 'Sliding', 'crud/pagination_control.phtml', $this->urlParams
     ); ?>
    <span class="forms">
        <?php echo $this->jumpForm; ?>
        <?php echo $this->searchForm; ?>
    </span>
</div>
