<h1>hello</h1>
<table class="zebra-striped">
<thead>
<?php foreach ($this->cols as $column): ?>
    <th><?php echo $column['COLUMN_NAME']; ?></th>
<?php endforeach; ?>
</thead>
<tbody>
<?php foreach ($this->data as $row): ?>
<tr>
<?php foreach ($row as $col => $val): ?>
    <td class="data-<?php echo $col; ?>"><?php echo $val; ?></td>
<?php endforeach; ?>
</tr>
<?php endforeach; ?>
</tbody>
</table>

<?php //exit;
