<div class="container">
    <div class="page-header-off">
        <h1><?php echo $this->ui_title; ?></h1>
    </div>
    <div class="row well">
        <a href="<?php echo $this->BetterUrl(array('action' => 'create')); ?>" class="btn btn-success small">
            Add new entry
        </a>
        <a href="<?php echo $this->BetterUrl(array('action' => 'list')); ?>?reset=1" class="btn btn-info small">
            Show all
        </a>
        <div class="pull-right"><?php echo $this->searchForm; ?></div>
    </div>

    <form action="<?php echo $this->BetterUrl(array('action' => 'bulk')); ?>" method="post">
    <table class="table table-striped">
    <thead>
        <tr>
<?php foreach ($this->cols as $column): ?>
    <?php
        $ordered = ($column == $this->order);
        $order = $ordered ? $this->otNew : 'ASC';
        $link = $this->url(array_merge($this->urlParams, array('o' => $column, 'ot' => $order)));
    ?>
    <?php if ($ordered): ?>
            <th>
                <a href="<?php echo $link; ?>"><?php echo $column; ?></a>
                <span class="<?php echo ($order === 'ASC') ? 'glyphicon glyphicon-arrow-up' : 'glyphicon glyphicon-arrow-down'; ?>"></span>
            </th>
    <?php else: ?>
            <th><a href="<?php echo $link ?>"><?php echo $column; ?></a></th>

    <?php endif; ?>

<?php endforeach; ?>
            <th>actions</th>
<?php if (!empty($this->bulkDelete)): ?>
            <th>delete</th>
<?php endif; ?>
        </tr>
    </thead>
    <tbody>
<?php foreach ($this->paginator as $row): ?>
        <tr>
<?php $_primary = array(); ?>
<?php foreach ($row as $col => $val): ?>

    <?php
    if (in_array($col, $this->primary)) {
        $_primary[$col] = $val;
    }
    ?>
    <?php if (in_array($col, $this->cols)): ?>
            <td class="data-<?php echo $col; ?>"><?php echo $val; ?></td>
    <?php endif; ?>
<?php endforeach; ?>
            <td style="width: 60px;">
                <a class="btn btn-default btn-xs" href="<?php echo $this->BetterUrl(array('action' => 'read', 'primary-key' => serialize($_primary))); ?>">
                    Detail
                </a>
            </td>
<?php if (!empty($this->bulkDelete)): ?>
            <td style="text-align: center; width: 45px;">
                <input type="checkbox" value="<?php echo urlencode(serialize($_primary)); ?>" name="bulk[]" />
            </td>
<?php endif; ?>
        </tr>
<?php endforeach; ?>
    </tbody>
    </table>

<?php if (!empty($this->bulkDelete)): ?>
        <button type="submit" class="btn btn-danger" style="float: right; margin: 5px 20px 0 0;">
            Bulk Delete selected Entries
        </button>
<?php endif; ?>
    </form>

<?php
     echo $this->paginationControl(
            $this->paginator, 'Sliding', 'crud/pagination_control.phtml', $this->urlParams
     );
?>

    <div class="row">
        <div class="well"><?php echo $this->jumpForm; ?></div>
    </div>
</div>
