<?php if ($this->pageCount): ?>
<div class="pagination">
<ul>
<?php if (isset($this->previous)): ?>
  <li><a href="<?php echo $this->first . $this->orderParams; ?>">
     &lt;&lt; First
  </a></li>
  <li class="prev"><a href="<?php echo $this->previous . $this->orderParams; ?>">
    &lt; Previous
  </a></li>
<?php else: ?>
  <li class="disabled"><a href="#">&lt;&lt;First</a></li>
  <li class="prev disabled"><a href="#">&lt; Previous</a></li>
<?php endif; ?>

<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <li class="active"><a href="<?php echo $page . $this->orderParams; ?>">
      <?php echo $page; ?>
    </a></li>
  <?php else: ?>
    <li><a href="#"><?php echo $page; ?></a></li>
  <?php endif; ?>
<?php endforeach; ?>

<?php if (isset($this->next)): ?>
  <li class="nex"><a href="<?php echo $this->next . $this->orderParams; ?>">
    Next &gt;
  </a></li>
  <li class="nex"><a href="<?php echo $this->last . $this->orderParams; ?>">
    Last &gt;&gt;
  </a></li>
<?php else: ?>
  <li class="nex disabled"><a href="#">Next &gt;</a></li>
  <li class="disabled"><a href="#">Last &gt;&gt;</a></li>
<?php endif; ?>
  </ul>
</div>
  <p>
    Page <?php echo $this->current; ?> of <?php echo $this->last; ?>
  </p>
<?php endif; ?>
