<?php if ($this->pageCount): ?>
<div class="pagination">
<ul>
<?php if (isset($this->previous)): ?>
  <li><a href="<?php echo $this->url(array_merge($this->params, array('p' => $this->first))); ?>">
     &lt;&lt; First
  </a></li>
  <li class="prev"><a href="<?php echo $this->url(array_merge($this->params, array('p' => $this->previous))); ?>">
    &lt; Previous
  </a></li>
<?php else: ?>
  <li class="disabled"><a href="#">&lt;&lt;First</a></li>
  <li class="prev disabled"><a href="#">&lt; Previous</a></li>
<?php endif; ?>

<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <li class="active"><a href="<?php echo $this->url(array_merge($this->params, array('p' => $page))); ?>">
      <?php echo $page; ?>
    </a></li>
  <?php else: ?>
    <li><a href="#"><?php echo $page; ?></a></li>
  <?php endif; ?>
<?php endforeach; ?>

<?php if (isset($this->next)): ?>
  <li class="nex"><a href="<?php echo $this->url(array_merge($this->params, array('p' => $this->next))); ?>">
    Next &gt;
  </a></li>
  <li class="nex"><a href="<?php echo $this->url(array_merge($this->params, array('p' => $this->last))); ?>">
    Last &gt;&gt;
  </a></li>
<?php else: ?>
  <li class="nex disabled"><a href="#">Next &gt;</a></li>
  <li class="disabled"><a href="#">Last &gt;&gt;</a></li>
<?php endif; ?>
  </ul>
  <h5>&nbsp;&nbsp;Page <?php echo $this->current; ?> of <?php echo $this->last; ?></h5>
</div>
<?php endif; ?>
