    <ul class="pills">
         <li <?php if ($this->action == 'list') { echo 'class="active"'; } ?>>
             <a href="<?php echo $this->BetterUrl(array('action' => 'list')); ?>">Show all</a>
         </li>
         <li <?php if ($this->action == 'read') { echo 'class="active"'; } ?>>
             <a href="<?php echo $this->BetterUrl(array('action' => 'read', $this->primary[0] => $this->pkValue)); ?>">Detail</a>
         </li>
         <li <?php if ($this->action == 'edit') { echo 'class="active"'; } ?>>
             <a href="<?php echo $this->BetterUrl(array('action' => 'edit', $this->primary[0] => $this->pkValue)); ?>">Edit</a>
         </li>
         <li <?php if ($this->action == 'delete') {echo 'class="active"'; } ?>>
             <a href="<?php echo $this->BetterUrl(array('action' => 'delete', $this->primary[0] => $this->pkValue)); ?>">Delete</a>
         </li>
    </ul>
