<ul class="nav nav-pills">
     <li <?php if ($this->requestAction == 'list') { echo 'class="active"'; } ?>>
         <a href="<?php echo $this->BetterUrl(array('module' => $this->requestModule, 'action' => 'list')); ?>">Show all</a>
     </li>
     <li <?php if ($this->requestAction == 'read') { echo 'class="active"'; } ?>>
         <a href="<?php echo $this->BetterUrl(array('module' => $this->requestModule, 'action' => 'read', $this->primary[0] => $this->pkValue)); ?>">Detail</a>
     </li>
     <li <?php if ($this->requestAction == 'edit') { echo 'class="active"'; } ?>>
         <a href="<?php echo $this->BetterUrl(array('module' => $this->requestModule, 'action' => 'edit', $this->primary[0] => $this->pkValue)); ?>">Edit</a>
     </li>
     <li <?php if ($this->requestAction == 'delete') {echo 'class="active"'; } ?>>
         <a href="<?php echo $this->BetterUrl(array('module' => $this->requestModule, 'action' => 'delete', $this->primary[0] => $this->pkValue)); ?>">Delete</a>
     </li>
</ul>
